# define myself
model = "F5TTS_v1_Small"
ref_audio = "./data/myself.wav"
# If an empty "", transcribes the reference audio automatically.
ref_text = "这是参考录音，用于合成语音。"
gen_text = "大家好，我是凤鹏超，来自上海交通大学电子信息与电气工程学院二零二二级人工智能班。我迷恋乒乓飞舞的韵律、楚河汉界的玄机，更爱执笔绘就丹青、行至山河万里。虽然我不会说四川话，但是我正在说四川话。你们觉得我说的像不像呢？"
# File with text to generate. Ignores the text above.
ckpt_file = "ckpts/F5TTS_v1_Small_shanghai/interpolated_model_80000.pt_a3.0_b1.0_nFalse.pt"
vocab_file = "data/shanghai_pinyin/vocab.txt"
output_dir = "tests"
output_file = "myself_shanghai_x7.wav"
